services:
  sb-h2:
    build:
      context: . # Project root as context
      dockerfile: Dockerfile
    image: sb-h2-data-masking
    container_name: sb-h2-data-masking-container
    ports:
      - "8080:8080"  # Expose Spring Boot API externally
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped